homework_07/hasker/hasker/urls.py
import user.urls
import queryanswer.urls

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(user.urls, namespace='user')),
    path('', include(queryanswer.urls, namespace='queryanswer')),
]

homework_07/hasker/queryanswer/urls.py
from .views import QuestionsListView, AskQuestionView, QuestionDetailView, CreateVote, UpdateVote
from django.urls import path


app_name = 'queryanswer'


urlpatterns = [
    path('', QuestionsListView.as_view(), name='index'),
    path('ask/', AskQuestionView.as_view(), name='ask'),
    # path('question/<slug:slug>', QuestionDetailView.as_view(), name='question'),
    path('question/<int:pk>', QuestionDetailView.as_view(), name='question'),
    path('question/<int:question_id>/vote', CreateVote.as_view(), name='CreateVote'),
    path('question/<int:question_id>/vote/<int:pk>', UpdateVote.as_view(), name='UpdateVote')
]

homework_07/hasker/user/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from user.views import RegisterView, SettingsView

app_name = 'user'
urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('singup', RegisterView.as_view(), name='register'),
    path('settings', SettingsView.as_view(), name='settings'),
]

homework_07/hasker/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<title>Hasker site</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> -->
<link rel="stylesheet" href="{% static 'css/w3.css' %}">
<body>
<header class="w3-container w3-light-grey">
  <div class="w3-row-padding">
    <div class="w3-third">
        <a href="/"><h1>Hasker</h1></a>
    </div>
    <div class="w3-third w3-padding-24 w3-center-align">
        <form action="" method="post">
            <input class="w3-input w3-border w3-round-xxlarge" type="text" placeholder="Search">
        </form>
    </div>
    <div class="w3-third w3-padding-24 w3-right-align">
  		<a href="{% url 'user:login' %}" class="w3-text-blue">Login</a>
        <a href="{% url 'user:register' %}" class="w3-button w3-white w3-border w3-border-grey w3-round-large">Sung Up</a>
    </div>
  </div>
</header>
<div class="w3-container">
    <div class="w3-sidebar w3-bar-block" style="width:25%;right:0">
        <div class="w3-container w3-padding-16"></div>
 	        <a href="{% url 'queryanswer:ask' %}" class="w3-button w3-block w3-light-grey w3-border w3-border-grey w3-round-large" style="width:50%">Ask!</a>
            <h3 class="w3-bar-item">Trending</h3>
            <p><span class="w3-tag w3-large w3-blue w3-round ">100</span>  How to Python?</p>
            <p><span class="w3-tag w3-large w3-blue w3-round ">100</span>  How to PERL?</p>
        </div>
    </div>
    <div style="margin-right:25%">
        {% block content %}

        {% endblock content %}
    </div>
</div>
<script>
    function openTab(tabName) {
        var i;
        var x = document.getElementsByClassName("tab");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        document.getElementById(tabName).style.display = "block";
    }
</script>
</body>
</html>