homework_07/hasker/hasker/urls.py
import user.urls
import queryanswer.urls

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(user.urls, namespace='user')),
    path('', include(queryanswer.urls, namespace='queryanswer')),
]

homework_07/hasker/queryanswer/urls.py
from .views import QuestionsListView, AskQuestionView, QuestionDetailView, CreateVote, UpdateVote
from django.urls import path


app_name = 'queryanswer'


urlpatterns = [
    path('', QuestionsListView.as_view(), name='index'),
    path('ask/', AskQuestionView.as_view(), name='ask'),
    # path('question/<slug:slug>', QuestionDetailView.as_view(), name='question'),
    path('question/<int:pk>', QuestionDetailView.as_view(), name='question'),
    path('question/<int:question_id>/vote', CreateVote.as_view(), name='CreateVote'),
    path('question/<int:question_id>/vote/<int:pk>', UpdateVote.as_view(), name='UpdateVote')
]

homework_07/hasker/user/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from user.views import RegisterView, SettingsView

app_name = 'user'
urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('singup', RegisterView.as_view(), name='register'),
    path('settings', SettingsView.as_view(), name='settings'),
]

homework_07/hasker/queryanswer/models.py
from django.db import models
from django.urls.base import reverse
from django.conf import settings
from django.utils import timezone
from django.db.models.aggregates import Sum
import math


class HotQuestionManger(models.Manager):
    """Hot Question Manager"""
    def get_queryset(self):
        pass

    def hot_question(self):
        qs = self.get_queryset()
        qs = qs.annotate(
            vote_sum=Sum('vote_value')
        )
        qs = qs.exclude(
            vote_sum=None
        )
        qs = qs.order_by('-vote_sum')
        return qs

class Question(models.Model):
    slug = models.SlugField('Url', max_length=150, unique=True)
    title = models.CharField('Заголовок ', default='', max_length=120)
    body = models.TextField('Содержание')
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, verbose_name='Автор: ', on_delete=models.CASCADE)
    created = models.DateTimeField('Создано', auto_now_add=True)
    tags = models.CharField('Теги', max_length=50)

    objects = models.Manager()

    class Meta:
        db_table = 'question'
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('queryanswer:question', kwargs={'pk': self.id})

    def can_accept_answer(self, user):
        return user == self.user

    def timeago(self):
        now = timezone.now()
        timediff = now - self.created
        if timediff.days == 0 and timediff.seconds >= 0 and timediff.seconds < 60:
            seconds = timediff.seconds
            if seconds == 1:
                return "asked " + str(seconds) + "second ago"
            else:
                return "asked " + str(seconds) + "seconds ago"
        
        if timediff.days == 0 and timediff.seconds >= 60 and timediff.seconds < 3600:
            minutes = math.floor(timediff.seconds / 60)

            if minutes == 1:
                return "asked " + str(minutes) + " minute ago"

            else:
                return "asked " + str(minutes) + " minutes ago"

        if timediff.days == 0 and timediff.seconds >= 3600 and timediff.seconds < 86400:
            hours = math.floor(timediff.seconds / 3600)

            if hours == 1:
                return "asked " + str(hours) + " hour ago"

            else:
                return "asked " + str(hours) + " hours ago"

            # 1 day to 30 days
        if timediff.days >= 1 and timediff.days < 30:
            days = timediff.days

            if days == 1:
                return "asked " + str(days) + " day ago"

            else:
                return "asked " + str(days) + " days ago"

        if timediff.days >= 30 and timediff.days < 365:
            months = math.floor(timediff.days / 30)

            if months == 1:
                return "asked " + str(months) + " month ago"

            else:
                return "asked " + str(months) + " months ago"

        if timediff.days >= 365:
            years = math.floor(timediff.days / 365)

            if years == 1:
                return "asked " + str(years) + " year ago"

            else:
                return "asked " + str(years) + " years ago"


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.TextField('Ответ:', default='')
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField('Создано:', auto_now_add=True)
    accept = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)
        db_table = 'answer'
    def __str__(self):
        return self.answer


class VoteManager(models.Manager):
    def get_vote_or_unsaved_blank_vote(self, question, user):
        try:
            return Vote.objects.get(
                question=question,
                user=user)
        except Vote.DoesNotExist:
            return Vote(
                question=question,
                user=user)


class Vote(models.Model):
    UP = 1
    DOWN = -1
    CHOICES  = (
        (UP, ">"),
        (DOWN, "<")
    )
    value = models.SmallIntegerField(choices=CHOICES)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)
    # votes = models.IntegerField(default=0)

    objects = VoteManager()

    class Meta:
        unique_together = ('user', 'question')

    def __str__(self):
        return str(self.value)

homework_07/hasker/queryanswer/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Question, Answer, Vote


class QuestionForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True
    )

    class Meta:
        model = Question
        fields = ['slug', 'title', 'body', 'tags','user']

class AnswerForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True
    )

    class Meta:
        model=Answer
        fields = ['answer', ]

class VoteForm(forms.ModelForm):

    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True
    )
    question = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Question.objects.all(),
        disabled=True
    )

    value = forms.ChoiceField(
        label="Vote",
        widget=forms.RadioSelect,
        choices=Vote.CHOICES
    )

    class Meta:
        model = Vote
        fields = ['value', 'user', 'question']

homework_07/hasker/queryanswer/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseBadRequest
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from .models import Question, Vote
from .forms import QuestionForm, AnswerForm
from django.views.generic import FormView
from django.views.generic.edit import FormMixin
from django.urls import reverse
from .forms import VoteForm
from django.shortcuts import redirect
from django.core.exceptions import PermissionDenied


class QuestionsListView(ListView):
    template_name = 'queryanswer/index.html'
    context_object_name = 'questions'
    paginate_by = 20
    model = Question


class HotQuestionsListView(ListView):
    template_name = 'queryanswer/index.html'
    # queryset = Question.objects.hot_question()


class AskQuestionView(LoginRequiredMixin, CreateView):
    form_class = QuestionForm
    template_name = 'queryanswer/ask.html'

    def get_initial(self):
        return {
            'user': self.request.user.id,
        }

    def form_valid(self, form):
       return super().form_valid(form)


class QuestionDetailView(DetailView, FormMixin):
    model = Question
    template_name = 'queryanswer/question.html'
    form_class = AnswerForm

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                question=self.object,
                user=self.request.user
            )
            if vote.id:
                vote_form_url = reverse(
                    'queryanswer:UpdateVote',
                    kwargs = {
                        'question_id': vote.question.id,
                        'pk': vote.id
                    }
                )
            else:
                vote_form_url = (
                    reverse(
                        'queryanswer:CreateVote',
                        kwargs={
                            'question_id': self.object.id
                        }
                    )
                )
            vote_form = VoteForm(instance=vote)
            ctx['vote_form'] = vote_form
            ctx['vote_form_url'] = vote_form_url

        return ctx


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['question'] = self.kwargs['question_id']
        return initial

    def get_success_url(self):
        question_id = self.object.question.id
        return reverse(
            'queryanswer:question',
            kwargs = {
                'pk': question_id})

    def render_to_response(self, context, **response_kwargs):
        question_id = context['object'].id
        print(question_id)
        question_detail_url = reverse(
            'queryanswer:question',
            kwargs= {'pk': question_id})
        return redirect(to=question_detail_url)


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied(
                'can not change another users vote')
        return vote

    def get_success_url(self):
        question_id = self.object.question.id
        return reverse(
            'queryanswer:question',
            kwargs={
                'pk': question_id})

    def render_to_response(self, context, **response_kwargs):
        question_id = context['object'].id
        question_detail_url = reverse(
            'queryanswer:question',
            kwargs={
                'pk': question_id})
        return redirect(to=question_detail_url)

homework_07/hasker/queryanswer/templates/queryanswer/ask.html
{% extends 'base.html' %}

{% block content %}
    <h2>Ask a question!</h2>
    {% if preview %}
        prev
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button name="action" value="SAVE">Ask!</button>
    </form>
{% endblock content %}

homework_07/hasker/queryanswer/templates/queryanswer/index.html
{% extends 'base.html' %}
{% block content %}
<div class="w3-container">
    <div class="w3-row">
        <div class="w3-container w3-center">
            <div class="w3-bar">
                <a class="w3-button" onclick="openTab('new')"><h3>New questions</h3></a>
                <a class="w3-button" onclick="openTab('hot')"><h3>Hot questions</h3></a>
            </div>
        </div>
        <div id="new" class="w3-container w3-display-container tab">
            {% for question in questions %}
            <!--Row-->
            <div class="w3-cell-row w3-border-top">
                <div class="w3-row">
                    <div class="w3-col w3-container" style="width:20%">
                        <div class="w3-half w3-container w3-center">
                            <p class="w3-xlarge">45</p>
                            <p>Votes</p>
                        </div>
                        <div class="w3-half w3-container w3-center">
                            <p class="w3-xlarge">{{ question.answer_set.count }}</p>
                            <p>Answers</p>
                        </div>
                    </div>
                    <div class="w3-col w3-container" style="width:60%">
                        <a href="{% url 'queryanswer:question' question.id %}"><h4>{{ question.title}}</h4></a>
                        <p>{{ question.body | truncatechars:200}}</p>
                        <div class="w3-margin-bottom">
                            <a href="#"><span class="w3-tag w3-blue w3-padding-small">Tag1</span></a>
                            <a href="#"><span class="w3-tag w3-blue w3-padding-small">Tag2</span></a>
                            <a href="#"><span class="w3-tag w3-blue w3-padding-small">Tag3</span></a>
                        </div>
                    </div>
                    <div class="w3-col w3-container" style="width:20%">
                        <br/><br/>
                        <a href="{% url 'user:settings' %}" class="w3-text-blue">{{ question.user }}</a>
                        <p class="w3-small">{{  question.timeago}}</p>
                    </div>
                </div>
            </div>
            <!--End Row-->
            {% empty %}
             <div class="w3-cell-row w3-border-top">
                <div class="w3-row">
                    <p>Вопросы отсутствуют!</p>
                </div>
             </div>
            {% endfor %}
        </div>
        <div id="hot" class="w3-container w3-display-container tab" style="display:none">
            <div class="w3-cell-row w3-border-top">
                <h3>h1</h3>
            </div>
            <div class="w3-cell-row w3-border-top">
                <h3>h2</h3>
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <div class="w3-row w3-center w3-border-top w3-padding-24">
        <div class="w3-bar">
            <a href="{% url 'queryanswer:index' %}?page=1" class="w3-button w3-round">&laquo;</a>
            {% if page_obj.has_previous %}
            <a href="{% url 'queryanswer:index' %}?page={{ page_obj.previous_page_number }}" class="w3-button w3-round">
                {{page_obj.previous_page_number}}
            </a>
            {% endif %}
            <a href="{% url 'queryanswer:index' %}?page={{ page_obj.number }}" class="w3-button w3-round">
                {{page_obj.number}}
            </a>
            {% if page_obj.has_next %}
            <a href="{% url 'queryanswer:index' %}?page={{ page_obj.next_page_number }}" class="w3-button w3-round">
                {{page_obj.next_page_number}}
            </a>
            {% endif %}
            <a href="{% url 'queryanswer:index' %}?page={{ page_obj.last }}" class="w3-button w3-round">&raquo;</a>
        </div>
    </div>
    {% endif %}
</div>
{% endblock content %}

homework_07/hasker/queryanswer/templates/queryanswer/question.html
{% extends 'base.html' %}

{% block content %}
<div class="w3-container">
    <div class="w3-row" >
        <div class="w3-third w3-container"></div>
        <div class="w3-rest w3-container w3-padding-32">
            <h3><a href="#">{{ question.title }}</a></h3>
            {{ question.body }}
            <div class="w3-margin-bottom">
                <span class="w3-tag w3-blue w3-padding-small">Tag1</span>
                <span class="w3-tag w3-blue w3-padding-small">Tag2</span>
                <span class="w3-tag w3-blue w3-padding-small">Tag3</span>
            </div>
        </div>
    </div>
    <!--End Row-->
    <!--Start Row-->
    <div class="w3-row" >
        <div class="w3-third w3-container"></div>
        <div class="w3-rest w3-container w3-border-bottom">
            <h3>Answer</h3>
        </div>
    </div>
    {% for item in question.answer_set.all %}

    <!--Start Answer-->
    <div class="w3-row" >
        <div class="w3-third w3-container"></div>
        <div class="w3-rest w3-container w3-margin-bottom w3-border-bottom">
            {{ item.answer }}
            <div class="w3-margin-bottom">
                <span class="w3-tag w3-blue w3-padding-small">Tag1</span>
                <span class="w3-tag w3-blue w3-padding-small">Tag2</span>
                <span class="w3-tag w3-blue w3-padding-small">Tag3</span>
            </div>
            <p><a href="">{{ item.user }}</a></p>
        </div>
    </div>
    <!--End Answer-->

    {% endfor %}
    <!--Start add Answer Form-->
    <div class="w3-row" >
        <div class="w3-third w3-container"></div>
        <div class="w3-rest w3-container w3-border-bottom">
            <h3>Your Answer</h3>
            <form action="">
                <textarea name="" id="" cols="80" rows="10"></textarea><br><br>
                <button>Submit</button>
            </form>
        </div>
    </div>
    <!--End add Answer Form -->
</div>
{% endblock content %}